### ISSUE TITLE
test_missing and test_partially_missing_data are identical

### ISSUE THREAD

**Issue by markgoddard** [valeriupredoi/PyActiveStorage#101]
These two tests in tests/test_missing.py are currently identical.

**Comment by bnlawrence** [comment]
Ok, I eventually worked out what you meant. You mean this:
```
def test_partially_missing_data(tmp_path):
    testfile = str(tmp_path / 'test_partially_missing_data.nc')
    r = dd.make_partially_missing_ncdata(testfile)
    _doit(testfile)

def test_missing(tmp_path):
    testfile = str(tmp_path / 'test_missing.nc')
    r = dd.make_partially_missing_ncdata(testfile)
    _doit(testfile)
```
means we have replicated the partially missing test, and the second one should have been a standard missing test.  Then, yes, I agree, the second one should be `dd.make_make_missing_ncdata(testfile)` ... but it would have been nice to have been this explicit.
