### ISSUE TITLE
Missing data integration tests are not testing missing data correctly

### ISSUE THREAD

**Issue by markgoddard** [valeriupredoi/PyActiveStorage#110]
## Synopsis

The S3 active storage server does not currently support missing data, therefore we would expect the tests in `tests/test_missing.py` to fail when `USE_S3` is true. However, they do not.

We can verify this with the following change to remove the missing data support from the local storage driver:

```
diff --git a/activestorage/storage.py b/activestorage/storage.py
index c66f536..9037977 100644
--- a/activestorage/storage.py
+++ b/activestorage/storage.py
@@ -41,8 +41,8 @@ def reduce_chunk(rfile, offset, size, compression, filters, missing, dtype, shap
 
     tmp = chunk[chunk_selection]
     if method:
-        if missing != (None, None, None, None):
-            tmp = remove_missing(tmp, missing)
+        #if missing != (None, None, None, None):
+        #    tmp = remove_missing(tmp, missing)
         # check on size of tmp; method(empty) returns nan
         if tmp.any():
             return method(tmp), tmp.size
```

Running the missing data tests (with USE_S3 = False), we see that only one test fails:

```
FAILED tests/test_missing.py::test_partially_missing_data - AssertionError:
```

## Cause of problem

As @markgoddard points out, the partial_missing test is the only one to fail because the test file that gets created is the only one of the (partial_missing, missing, fillvalue) group that contains valid missing data (masked data), the other two test files do not contain any missing/fillvalue values, here attaching the files (with .txt extension so GH can allow upload)

@bnlawrence `dummy_data.py/make_ncdata()` needs fixing please :beer: 

[Issue110_partially_missing.nc.txt](https://github.com/valeriupredoi/PyActiveStorage/files/11983443/Issue110_partially_missing.nc.txt)
[Issue110_missing.nc.txt](https://github.com/valeriupredoi/PyActiveStorage/files/11983446/Issue110_missing.nc.txt)
[Issue110_FillValue.nc.txt](https://github.com/valeriupredoi/PyActiveStorage/files/11983450/Issue110_FillValue.nc.txt)

**Comment by valeriupredoi** [comment]
@markgoddard think we can close this too, since now we actually have USE_S£ correctly set in the test env and we are xfailing these tests :beer:

**Comment by markgoddard** [comment]
I think it's still valid. My logic is that because S3 doesn't support missing data, those tests should fail, but they do not. So the tests must not be testing the right thing.

If you apply the diff in the description to break missing data support for local files, you'll see that the tests still pass, which of course they should not.

**Comment by valeriupredoi** [comment]
aha, right on! I shall investigate then :beer:

**Comment by valeriupredoi** [comment]
@markgoddard don't mind my initial moaning about this, mate - this is indeed exposing some nasty stuff going on: so I am doing verifications in https://github.com/valeriupredoi/PyActiveStorage/pull/122 and, bar a few initial sanity checks that passed (yeh indeed USE_S3=True, storage_type="s3", data actually contains masked values at lookup point etc, so nominal run parameters), the missing/fillvalue handling appears to be a bit broken, as far as I can see at least in one place:

- `test_partially_missing_data` returns a result of 796 in the non-S3 case, but the same test returns a result of -101,5 when using S3 (see [GA run](https://github.com/valeriupredoi/PyActiveStorage/actions/runs/5487148114/jobs/9998202074?pr=122) ) and, knowing that the missing value is set to -999., this suggests that the non-S3 computation does indeed treat those -999 as missing data, but the S3 element uses them as valid data values;
- the other results in the other test cases are identical for both non-S3 and S3 cases, which suggests that either both non-S3 and S3 handling of missing/fillvalue is wrong, or both are correct :grin: Knowing the non-S3 is correct, I assume the S3 side of the computation has a side-effect leading to a correct handling of the missing values, you sure this:
```python
count = reduce_chunk(server, username, password, source, bucket, object, offset, size, compression, filters, missing, dtype, shape, order, chunk_selection, "count")[0]
```
is not actually doing the right thing?

**Comment by valeriupredoi** [comment]
nevermind! I just took a closer look at the data in the test files for missing and fillvalues - @bnlawrence will get an issue in a few minutes to fix the actual missing/fillvalue test data creation - **there are literally no missing or fillvalues** values (no -999 or no masked elements) in the missing/fillvalue test cases, so no wonder those tests return identical results for both non-S3 and S3 cases :man_facepalming:

**Comment by markgoddard** [comment]
> @markgoddard don't mind my initial moaning about this, mate - this is indeed exposing some nasty stuff going on: so I am doing verifications in #122 and, bar a few initial sanity checks that passed (yeh indeed USE_S3=True, storage_type="s3", data actually contains masked values at lookup point etc, so nominal run parameters), the missing/fillvalue handling appears to be a bit broken, as far as I can see at least in one place:
> 
> * `test_partially_missing_data` returns a result of 796 in the non-S3 case, but the same test returns a result of -101.5 when using S3 (see [GA run](https://github.com/valeriupredoi/PyActiveStorage/actions/runs/5487148114/jobs/9998202074?pr=122) ) and, knowing that the missing value is set to -999., this suggests that the non-S3 computation does indeed treat those -999 as missing data, but the S3 element uses them as valid data values;
> * the other results in the other test cases are identical for both non-S3 and S3 cases, which suggests that either both non-S3 and S3 handling of missing/fillvalue is wrong, or both are correct grin Knowing the non-S3 is correct, I assume the S3 side of the computation has a side-effect leading to a correct handling of the missing values, you sure this:
> 
> ```python
> count = reduce_chunk(server, username, password, source, bucket, object, offset, size, compression, filters, missing, dtype, shape, order, chunk_selection, "count")[0]
> ```
> 
> is not actually doing the right thing?

You're saying it's more likely that I accidentally implemented missing data support without realising it than the non-S3 code is wrong? :joy: 

Sounds like you're onto it though.

One thing I had wondered is whether the selection was ignoring the missing data.
