### ISSUE TITLE
Improve unit testing of Active with s3 storage type

### ISSUE THREAD

**Issue by markgoddard** [valeriupredoi/PyActiveStorage#114]
Currently the test_storage_types.py unit test has only one test with a simple assertion:

```
    with pytest.raises(botocore.exceptions.ParamValidationError):
        Active(os.path.join(active_url, s3_testfile), "data", "s3")
```

This relies on an early failure in `load_from_s3` when reading the netCDF metadata from S3.

Let's instead mock out any interaction with remote systems, and replace with the expected behaviour.

**Comment by valeriupredoi** [comment]
we merged #115 can we close this or should we expect more test enhancement related to this issue? :beer:

**Comment by markgoddard** [comment]
Argh, I missed the Closes comment. Further work could (always) be done, but not planning to at this time. Ready to close.

**Comment by valeriupredoi** [comment]
yay! :beer:
