### ISSUE TITLE
Add support for compressed and shuffled datasets on local storage

### ISSUE THREAD

**Issue by markgoddard** [valeriupredoi/PyActiveStorage#118]
Currently if a dataset is compressed or has any filters applied, PyActiveStorage will raise `NotImplementedError` in storage.py.

There are many compression and filter algorithms supported by netCDF/HDF5, but this task covers supporting and testing the Zlib compression algorithm as well as the HDF5 Shuffle filter. This task covers support for local storage. S3 will be addressed separately.

**Comment by valeriupredoi** [comment]
this is indeed now done and tested (cheers very much @markgoddard ) - testing done on real CMIP6 and obs4MIPS (compressed, shuffle=False) too.  Worth noting that there was some discussion to follow up from https://github.com/valeriupredoi/PyActiveStorage/pull/119#discussion_r1258097057
