### ISSUE TITLE
Add compression and filters to the storage interface even if we don't use them for now?

### ISSUE THREAD

**Issue by bnlawrence** [valeriupredoi/PyActiveStorage#12]
We are not planning on supporting compression during this development project, but  be useful in reality, compression will be needed. As we now have all the machinery in place to get at entire chunks, we could hand  compression and filter requirements into the storage layer as well - where they could be ignored until the storage folk want to support them.

**Comment by bnlawrence** [comment]
We don't need to keep this open while waiting for code and doc cleanups.

**Comment by valeriupredoi** [comment]
I am more of the "keep issues open until they get solved or die of old age" adept, @bnlawrence - but that's fine, we'll brifge it when we get to it
