### ISSUE TITLE
Passing missing data values to constructor fails with S3 storage backend

### ISSUE THREAD

**Issue by markgoddard** [valeriupredoi/PyActiveStorage#137]
For example:
```
uri = "s3://bucket/object.nc"
Active(uri, "ta", "s3", missing_value=999.)
```

This uses a different code path which avoids loading the netCDF file metadata. Since #132 merged, this no longer works when using the S3 storage backend because we need to get the dtype from the metadata. It fails in the following way:

```
AttributeError: 'Active' object has no attribute '_dtype'
```

A simple solution is to always load the netCDF metadata. This has the downside that it is not necessary when using local storage and missing data has been specified.

**Comment by valeriupredoi** [comment]
this could bite the RED storage fellas as well since that's POSIX but custom, and not local - am gonna add Konstantinos and JT to this repo as well, and will tag them here even if we close after merging the PR
