### ISSUE TITLE
Documentation-related dependencies

### ISSUE THREAD

**Issue by davidhassell** [valeriupredoi/PyActiveStorage#195]
Hi V - could we remove the docs-related dependencies: https://github.com/valeriupredoi/PyActiveStorage/blob/main/environment.yml#L28-L31 ? They don't affect the running of the code, so can only serve to cause havoc when installing into an existing environment. Thanks
```
  # Python packages needed for building docs
  - autodocsumm >=0.2.2
  - sphinx >=5
  - sphinx_rtd_theme
```

**Comment by valeriupredoi** [comment]
I will temporarily comment them out - until we decide what to use for docs building, good call, David!

**Comment by davidhassell** [comment]
Ta!
