### ISSUE TITLE
Optional file lock to prevent concurrent reads with the netCDF-C library

### ISSUE THREAD

**Issue by davidhassell** [valeriupredoi/PyActiveStorage#57]
When parallelising `Active.__getitem__` operations across process threads, it will be necessary to lock any file reads by the netCDF-C library because these are not thread-safe.

**Comment by davidhassell** [comment]
Hi - In the PR #58 , I put in a placeholder for locking a local reduction, but that's assuming the HDF5 library is being used. Is this the case?

**Comment by valeriupredoi** [comment]
yes, via `netcdf4` and `h5py` which are direct dependencies here, bud - see our [environment](https://github.com/valeriupredoi/PyActiveStorage/blob/main/environment.yml)

**Comment by davidhassell** [comment]
Thanks, V. Then the non-active, local reduction will indeed need locking.
