### ISSUE TITLE
To do from PR 5 - OrthogonalIndexer

### ISSUE THREAD

**Issue by valeriupredoi** [valeriupredoi/PyActiveStorage#6]
@bnlawrence says:

Ok, this is now in a state we can share on Friday! (NB https://github.com/valeriupredoi/hdf5_kerchunk_zarr/pull/5) The only thing left would be to add a layer to the call stack to strip the need to use the Orthogonalndexer out in the same place as we start on processing chunks. Ideally we use the OrthogonalIndexer in the Python call stack and everything below can then be reimplemented by the storage folks without need for importing zarr.

**Comment by bnlawrence** [comment]
That's been done in my latest set of pull requests!
