### ISSUE TITLE
S3 reduce chunk needs to always return count

### ISSUE THREAD

**Issue by bnlawrence** [valeriupredoi/PyActiveStorage#91]
The current implementation of [s3 reduce chunk](https://github.com/valeriupredoi/PyActiveStorage/blob/5becf10d3b44d4344d618db3f00c49e51706d9f0/activestorage/s3.py#L10) requires two calls via S3 in the case where it is asking for a mean.

The current implementation of [python reduce chunk](https://github.com/valeriupredoi/PyActiveStorage/blob/5becf10d3b44d4344d618db3f00c49e51706d9f0/activestorage/storage.py#L6) always returns the result of the method and the count of items over which the method was applied  (e.g. [here](https://github.com/valeriupredoi/PyActiveStorage/blob/5becf10d3b44d4344d618db3f00c49e51706d9f0/activestorage/storage.py#L47)). 

It would be better for S3 that it always did this too, which means a change to both our python s3 reduce chunk (and the [decode result](https://github.com/valeriupredoi/PyActiveStorage/blob/5becf10d3b44d4344d618db3f00c49e51706d9f0/activestorage/s3.py#L105) method within it) ,

_and_ 

the server side response from https://github.com/stackhpc/s3-active-storage-rs. 
(So there will need to be a matching issue there.)

**Comment by markgoddard** [comment]
Server side PR: https://github.com/stackhpc/s3-active-storage-rs/pull/44

**Comment by valeriupredoi** [comment]
cheers very much @markgoddard :beer: And hope hols were good :beach_umbrella:

**Comment by sd109** [comment]
Once we merge the server side PR for returning the count from requests to the proxy server (should be merged this week), would it make sense to remove the separate `/mean` and `/count` operation from our proxy API spec to avoid confusion? Or are there situations where we you still want to calculate just the count or just the mean of a single chunk?
